In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences

sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'this is word embedding technique']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'this is word embedding technique']

In [4]:
# Vocabulary size

voc_size = 10000

In [5]:
# One hot representation

onehot_repr = [one_hot(words, voc_size) for words in sent]

In [6]:
print(onehot_repr)

[[6737, 3832, 1884, 559], [6737, 3832, 1884, 961], [6737, 2317, 1884, 8459], [1384, 8360, 7461, 7806, 9377], [1384, 8360, 7461, 7806, 5804], [8456, 6737, 5518, 1884, 709], [114, 3366, 4019, 6307, 4388]]


In [7]:
## Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8

embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 6737 3832 1884  559]
 [   0    0    0    0 6737 3832 1884  961]
 [   0    0    0    0 6737 2317 1884 8459]
 [   0    0    0 1384 8360 7461 7806 9377]
 [   0    0    0 1384 8360 7461 7806 5804]
 [   0    0    0 8456 6737 5518 1884  709]
 [   0    0    0  114 3366 4019 6307 4388]]


In [11]:
# dimension

dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, 10 , input_length = sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]
  [-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]
  [-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]
  [-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]
  [ 0.00115399 -0.04230089  0.02477981 -0.02756917  0.02864579
    0.04638601  0.04974098  0.00390293  0.01583573  0.03876468]
  [-0.02449635  0.00203365 -0.00370019 -0.03475557  0.04533067
    0.03418161 -0.02386038 -0.0227603  -0.01016418  0.02997715]
  [-0.02753505 -0.03534652  0.0210238   0.00755786 -0.04817707
   -0.02742108  0.00658234 -0.02973217 -0.00445171 -0.01607914]
  [ 0.00692666  0.00681679  0.00448918  0.0226987  -0.01450808
   -0.02196714 -0.01552083  0.0470208  -0.017343

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 6737, 3832, 1884,  559], dtype=int32)

In [16]:
print(model.predict(embedded_docs[0]))

[[[-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]]

 [[-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]]

 [[-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]]

 [[-0.01563852  0.03497031 -0.04426459  0.0397417   0.01502884
    0.00257438 -0.00109515  0.01910276 -0.01571791  0.03276557]]

 [[ 0.00115399 -0.04230089  0.02477981 -0.02756917  0.02864579
    0.04638601  0.04974098  0.00390293  0.01583573  0.03876468]]

 [[-0.02449635  0.00203365 -0.00370019 -0.03475557  0.04533067
    0.03418161 -0.02386038 -0.0227603  -0.01016418  0.02997715]]

 [[-0.02753505 -0.03534652  0.0210238   0.00755786 -0.04817707
   -0.02742108  0.00658234 -0.02973217 -0.00445171 -0.01607914]]

 [[ 0.00692666  0.00681679  0.00448918  0.0226987  -0.01450808
   -0.02196714 -0.01552083  0.0470